### ISSUE TITLE
CANManager::Process()::_tick_time - Вынести в конструктор.

### ISSUE THREAD

**Issue by Dragon-Knight** [starfactorypixel/PixelCANLibrary#3]
Прошу вынести параметр `CANManager::Process()::_tick_time` в конструктор объекта в качестве 3'го параметра и использовать `10` как значение по умолчанию.

**Comment by GrKoR** [comment]
Выносим прямо в конструктор? Или в параметры темплейта?

У нас два варианта, как можем сделать:
Вариант 1:
```CANManager<CFG_CANObjectsCount, CFG_CANFrameBufferSize> can_manager(&HAL_CAN_Send, CFG_TickTime);```

Вариант 2:
```CANManager<CFG_CANObjectsCount, CFG_CANFrameBufferSize, CFG_TickTime> can_manager(&HAL_CAN_Send);```

Или всё равно?

**Comment by Dragon-Knight** [comment]
Да, шаблон, я описа'лся 🤷‍♂️
